export const templateConfig = {
  1: {
    name: { x: 85, y: 295 },
    details: { x: 130, y: 360 },
    namefont: "PlayfairDisplay",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "#e3c25e",
  },
  2: {
    name: { x: 83, y: 323 },
    details: { x: 145, y: 400 },
    namefont: "CinzelDecorative",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "white",
  },
  3: {
    name: { x: -25, y: 270 },
    details: { x: 50, y: 333 },
    namefont: "GreatVibes",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  4: {
    name: { x: 75, y: 275 },
    details: { x: 115, y: 350 },
    namefont: "Helios Retro",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  5: {
    name: { x: 225, y: 275 },
    details: { x: 215, y: 350 },
    namefont: "Jost",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "white",
  },
  6: {
    name: { x: 75, y: 305 },
    details: { x: 130, y: 390 },
    namefont: "Lakesight",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  7: {
    name: { x: 75, y: 285 },
    details: { x: 130, y: 355 },
    namefont: "Lakesight",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "white",
  },
  8: {
    name: { x: 55, y: 270 },
    details: { x: 125, y: 330 },
    namefont: "Merriweather",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "white",
  },
  9: {
    name: { x: 90, y: 275 },
    details: { x: 130, y: 345 },
    namefont: "Montserrat",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  10: {
    name: { x: 75, y: 285 },
    details: { x: 130, y: 355 },
    namefont: "NewAmsterdam",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  11: {
    name: { x: 15, y: 270 },
    details: { x: 95, y: 343 },
    namefont: "OpenSans",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  12: {
    name: { x: -115, y: 280 },
    details: { x: 20, y: 343 },
    namefont: "Parisienne",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  13: {
    name: { x: 66, y: 260 },
    details: { x: 130, y: 335 },
    namefont: "PinyonScript",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  14: {
    name: { x: 75, y: 335 },
    details: { x: 130, y: 405 },
    namefont: "PlayfairDisplay",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  15: {
    name: { x: 300, y: 265 },
    details: { x: 260, y: 343 },
    namefont: "Poppins",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  16: {
    name: { x: 75, y: 300 },
    details: { x: 130, y: 368 },
    namefont: "CinzelDecorative",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  17: {
    name: { x: 100, y: 297 },
    details: { x: 130, y: 368 },
    namefont: "CinzelDecorative",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  18: {
    name: { x: 75, y: 260 },
    details: { x: 130, y: 330 },
    namefont: "GreatVibes",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  19: {
    name: { x: 75, y: 285 },
    details: { x: 130, y: 355 },
    namefont: "Helios Retro",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  20: {
    name: { x: 120, y: 255 },
    align: "center",
    details: { x: 140, y: 340 },
    namefont: "Poppins",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 20,
    color: "black",
  },
  21: {
    name: { x: 80, y: 255 },
    align: "center",
    details: { x: 130, y: 320 },
    namefont: "Lakesight",
    descrpfont: "Montserrat",
    namefontSize: 60,
    descrpfontSize: 20,
    color: "white",
  },
  22: {
    name: { x: 66, y: 190 },
    details: { x: 130, y: 270 },
    namefont: "Lora-Italic",
    descrpfont: "Montserrat",
    namefontSize: 60,
    descrpfontSize: 20,
    color: "black",
  },
  23: {
    name: { x: 55, y: 260 },
    details: { x: 125, y: 334 },
    namefont: "Merriweather",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  24: {
    name: { x: 55, y: 296 },
    details: { x: 125, y: 358 },
    namefont: "Montserrat",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 15,
    color: "black",
  },
  25: {
    name: { x: 55, y: 290 },
    details: { x: 125, y: 355 },
    namefont: "NewAmsterdam",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "white",
  },
  26: {
    name: { x: 60, y: 295 },
    details: { x: 115, y: 350 },
    namefont: "OpenSans",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  27: {
    name: { x: 60, y: 295 },
    details: { x: 105, y: 350 },
    namefont: "Poppins",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  28: {
    name: { x: 250, y: 225 },
    details: { x: 205, y: 300 },
    namefont: "PinyonScript",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  29: {
    name: { x: 60, y: 275 },
    details: { x: 115, y: 350 },
    namefont: "PlayfairDisplay",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
  30: {
    name: { x: 70, y: 320 },
    details: { x: 130, y: 370 },
    namefont: "Poppins",
    descrpfont: "Montserrat",
    namefontSize: 32,
    descrpfontSize: 15,
    color: "black",
  },
  31: {
    name: { x: 425, y: 220 },
    details: { x: 130, y: 320 },
    namefont: "AlexBrush",
    descrpfont: "Montserrat",
    namefontSize: 32,
    descrpfontSize: 15,
    color: "black",
  },
  32: {
    name: { x: 70, y: 210 },
    details: { x: 130, y: 270 },
    namefont: "CinzelDecorative",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "black",
  },
  33: {
    name: { x: 70, y: 280 },
    details: { x: 130, y: 340 },
    namefont: "GreatVibes",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "black",
  },
  34: {
    name: { x: 70, y: 290 },
    details: { x: 130, y: 350 },
    namefont: "Helios Retro",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "black",
  },
  35: {
    name: { x: -200, y: 290 },
    details: { x: 0, y: 370 },
    namefont: "Jost",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "white",
  },
  36: {
    name: { x: 75, y: 300 },
    details: { x: 120, y: 390 },
    namefont: "Lakesight",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "white",
  },
  37: {
    name: { x: 75, y: 315 },
    details: { x: 120, y: 390 },
    namefont: "Lora-Italic",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "white",
  },
  38: {
    name: { x: 450, y: 205 },
    align: "right",
    details: { x: 240, y: 400 },
    namefont: "Merriweather",
    descrpfont: "Montserrat",
    namefontSize: 35,
    descrpfontSize: 15,
    color: "black",
  },
  39: {
    name: { x: 76, y: 265 },
    details: { x: 125, y: 340 },
    namefont: "Montserrat",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 17,
    color: "black",
  },
  40: {
    name: { x: 320, y: 265 },
    details: { x: 240, y: 330 },
    namefont: "Poppins",
    descrpfont: "Montserrat",
    namefontSize: 40,
    descrpfontSize: 12,
    color: "black",
  },
};

